name: Python Calculator CI

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  checks: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: python-example
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Run Tests
        run: |
          pytest test/ --cov=src --cov-report=xml

      - name: Upload coverage reports
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: inerplat/fastcampus-devops-testcode-example
          files: python-example/coverage.xml

  container:
    needs: test
    runs-on: ubuntu-22.04
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set Docker tag
        id: tag
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "tag=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "tag=${{ github.head_ref || github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: python-example
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.event.repository.name }}:${{ env.tag }}-python